# -*- coding: utf-8 -*-
from odoo import api, fields, models, SUPERUSER_ID, _
from datetime import date, datetime
from odoo.exceptions import UserError, ValidationError, MissingError


class TherapyRecordProduct(models.Model):
    _name = 'therapy.record.product'

    name = fields.Char('Therapy record product')
    therapy_record_id = fields.Many2one('therapy.record', string='Therapy Record')
    product_id = fields.Many2one('product.product', string='Product')
    # product_is_massage_id = fields.Many2one('product.product', related='product_id', domain=[('product_tmpl_id.x_is_injection', '=', 'False')], string='Product Is massage')
    uom_id = fields.Many2one('product.uom', string='Unit of  Measure')
    qty_used = fields.Integer(string='Quantity Used')
    qty_available = fields.Integer(string='Quantity available', compute='_compute_qty_available')
    qty_max = fields.Integer(string='Quantity Max')

    @api.onchange('product_id')
    def _onchange_product_id(self):
        if self.product_id:
            self.uom_id = self.product_id.product_tmpl_id.uom_id.id

    @api.depends('qty_used', 'qty_max')
    def _compute_qty_available(self):
        for s in self:
            s.qty_available = s.qty_max - s.qty_used
